name: 'Deploy Azure Resource Group with Terraform'

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

      run: cd 03-Terraform-Command-Basics/terraform-manifests

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Terraform Init'
      run: terraform init
      working-directory: 03-Terraform-Command-Basics/terraform-manifests

    - name: 'Terraform Plan'
      run: terraform Plan
      working-directory: 03-Terraform-Command-Basics/terraform-manifests 

    - name: 'Terraform Apply'
      run: terraform Apply
      working-directory: 03-Terraform-Command-Basics/terraform-manifests 
